### PR TITLE
Incorporating suggested changes to prevent brackets in final links of social media

### PR DESCRIPTION
**Pull request by rcmckee**
Incorporated suggested edits from https://github.com/freelawproject/bigcases2/pull/583#issuecomment-2327070111

### CODE REVIEW

**Comment by mlissner** [comment]
Thanks! We'll review ASAP!

**Review by ERosendo — APPROVED** [review]
@rcmckee Thanks for the PR. I've added a test to ensure correct functionality and prevent future regressions.

Here are posts using my Bluesky account: 

image


image

**Comment by mlissner** [comment]
Way better!

**Comment by mlissner** [comment]
Does this one just need to be merged, @ERosendo, @rcmckee?

**Comment by ERosendo** [comment]
@mlissner Yes

**Comment by mlissner** [comment]
Shoot, sorry to miss it, and good to have it done! Thank you both!

**Pull request merged**
