### PR TITLE
feat(html): Add an example button

### PR DESCRIPTION
**Pull request by mlissner**
This adds a basic example button leading to Twitter:

image

### CODE REVIEW

**Comment by mlissner** [comment]
I'm not feeling super confident with tailwind these days, so if there's a better way to do this, I'm happy to be corrected.

**Review by ERosendo — CHANGES_REQUESTED** [review]
This looks good. Just one comment about the spacing :)

**Comment by mlissner** [comment]
Cool, thanks. Will you approve the PR so it can auto-merge, please?

**Comment by ERosendo** [comment]
Sure!

**Review by ERosendo — APPROVED** [review]

**Pull request merged**
