### PR TITLE
feat(sentry): Add sentry support

### PR DESCRIPTION
**Pull request by ERosendo**
This PR fixes https://github.com/freelawproject/bigcases2/issues/31. 

This PR introduces the following changes:

- This PR creates a module for the `settings`  This approach allows us to split the settings by the source, so We can create a folder to store setting from third-party apps.

- Sentry-sdk is added as a dependency.

- This PR creates a file to store settings related to mastodon and sentry.

- An endpoint to trigger/test Sentry is added.

- This PR adds a CI task to generate sentry releases.

### CODE REVIEW

**Review by mlissner — APPROVED** [review]
Cool. Some conflicts I'm sure you'll resolve. Once you do, feel free to merge. 

Other than that, it looks great to me and I set the needed variables, so it should start working.

**Comment by ERosendo** [comment]
@mlissner I fixed the conflicts but I don't know why the release action is still failing

**Comment by mlissner** [comment]
Hm, it says:

> error: No commits found. Change commits range, initial depth or use --ignore-empty to allow empty patch sets.

I don't know why it'd think that, but my guess is because this is a new CI in this PR, so I'm going to ignore it. We'll see if it keeps being an issue (it probably will), and then we can try to dig in more deeply.

**Comment by mlissner** [comment]
Dang, more conflicts, but once resolved, go ahead and merge, please.

**Comment by ERosendo** [comment]
@mlissner I resolved the conflicts but I need your approval to merge this PR into to the main branch.

**Review by mlissner — APPROVED** [review]
Looks good to me.

**Pull request merged**
