### PR TITLE
chore(factories): expand Group- and Channel- Factories

### LINKED ISSUE #273: chore: add dummy data for big cases
When I first got the system up and running and went to http://localhost:8888/big-cases/about/, there were no big cases being followed. I assumed that the initial dummy data would at least have one big case being followed so that something would show up on this page. Having some cases on the big cases page would let people see how cases show up on the page and that they are connected to Court Listener.

Having richer data will make it easier for developers to see how the models and information is related.  (Will especially help developers new to the project.)

At a minimum, I think `bootstrap-dev` should also:
1. create a channel Group for big cases: `name = 'big cases', is_big_cases=True`
2. set the Mastodon channel to be in the 'big cases' Group
3. add 2 of the existing Subscriptions to the Mastodon channel. Having more than 1 case lets a developer play with more variations.

I'm happy to do this. (I've already done the above just so I could see it on the big-cases page.)

Is there other minimal data that should be added?
Perhaps a Twitter channel should also be added? (And it should also be set to the 'big cases' Group)

### PR DESCRIPTION
**Pull request by weedySeaDragon**
for #273

Add traits, documentation to GroupFactory and ChannelFactory. 
Also adds  `fake_token()` (used by ChannelFactory and potentially in tests)

Per #273, Expanded the factories so that they can be used to create some initial data for development:
- Created traits for commonly used factory configurations:
   - GroupFactory:  `big_cases` and `little_cases`
   - ChannelFactory: `mastodon` and `twitter`

- Added some sensible attribute defaults
- Added documentation

(Accidentally based this branch on the faker-citation-data-273 branch. Rebased onto main)

### CODE REVIEW

**Comment by mlissner** [comment]
I've added @ERosendo as a reviewer, thanks for this helpful work.

**Comment by ERosendo** [comment]
Looks good to me, but you've got a conflict and it needs a rebase, please (there are changes here from earlier PRs).

**Review by ERosendo — APPROVED** [review]
@weedySeaDragon thank you! 

@mlissner I think we can merge this PR :shipit:

**Comment by mlissner** [comment]
Thanks all!

**Pull request merged**
