### PR TITLE
feat(subscription): Add new argument to the lookup command

### PR DESCRIPTION
**Pull request by ERosendo**
This PR fixes https://github.com/freelawproject/bigcases2/issues/88 by adding a new argument called `name` to the `lookup` command

### CODE REVIEW

**Comment by mlissner** [comment]
This approach won't work because you won't necessarily know it's a really long name until after the case has been added. It should prompt you for the name instead, with the default set to whatever comes back from the API.

**Comment by ERosendo** [comment]
Got It! 

Will the command always prompt you for the name?

We can set a `max number of characters`, so the command will only prompt for the name when We get a string longer than the `max_number`.

let me know what you think.

**Comment by mlissner** [comment]
I would say it should just prompt you every time, but have a default, so pressing enter is all you have to do.

**Comment by ERosendo** [comment]
Cool. I'm going to refactor the command to that.

**Comment by ERosendo** [comment]
Here's some gifs showing the command:

for short names:
short-string-command

for long names:
long-string-command

Let me know what you think.

**Comment by mlissner** [comment]
You're close, but I'll be picky. The way it should work is it should prompt like this:

> Name (Hillary v. Trump): ▉

If you press enter it just does what's in the parens. If you don't, then you can type what you want.

**Comment by ERosendo** [comment]
I know that including the default value in the prompt between brackets is a fairly common convention but I tried that approach and I think It doesn't look clean when the default is a long string. Here's a gif showing the prompt using brackets:


long-string-command-brackets


It looks good for short string, though!

**Pull request merged**
